
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 02 21:02:04 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SQRT = 39;
  public static final int LTE = 30;
  public static final int MODIF_JAN = 48;
  public static final int CHAR = 41;
  public static final int CONST = 22;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 18;
  public static final int FOR = 16;
  public static final int MINUS = 23;
  public static final int RPAREN = 7;
  public static final int AND = 31;
  public static final int LT = 29;
  public static final int MINUS2 = 34;
  public static final int OR = 32;
  public static final int BOOL = 40;
  public static final int COMMA = 8;
  public static final int CLASS = 20;
  public static final int DIV = 38;
  public static final int PLUS = 11;
  public static final int IF = 45;
  public static final int DOT = 47;
  public static final int ABSTRACT = 21;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MUL = 37;
  public static final int NULL = 44;
  public static final int NUMBER = 42;
  public static final int MOD = 24;
  public static final int NEQ = 26;
  public static final int IDENT = 43;
  public static final int BREAK = 17;
  public static final int VOID = 13;
  public static final int EQ = 25;
  public static final int GTE = 28;
  public static final int ELSE = 46;
  public static final int LBRACE = 3;
  public static final int LSQUARE = 35;
  public static final int READ = 14;
  public static final int RSQUARE = 36;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int PLUS2 = 33;
  public static final int GT = 27;
  public static final int PRINT = 9;
}

